[package]
name = "myco-client"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco-http = { path = "../http" }
myco = { path = "../myco" }
log = "0.4.14"
async-net = "1.5.0"
url = "2.2.0"
futures-lite = "1.11.3"
httparse = "1.3.5"
memmem = "0.1.1"
async-tungstenite = "0.12.0"
async-lock = "2.3.0"
async-channel = "1.5.1"
futures-util = "0.3.12"
size = "0.1.2"
async-native-tls = "0.3.3"
async-tls = "0.11.0"
rustls = "0.19.0"
webpki-roots = "0.21.0"
rustls-native-certs = "0.5.0"

[dev-dependencies]
async-global-executor = "2.0.2"
env_logger = "0.8.3"
futures-util = "0.3.12"
async-io = "1.3.1"
fastrand = "1.4.0"
