[package]
name = "myco-example"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
env_logger = "0.8.2"
myco = { path = "../myco" }
myco-router = { path = "../router" }
myco-logger = { path = "../logger" }
myco-cookies = { path = "../cookies" }
myco-sessions = { path = "../sessions" }
myco-websockets = { path = "../websockets" }
myco-smol-server = { path = "../smol-server" }
myco-askama = { path = "../askama" }
futures-lite = "1.11.3"
askama = "0.10.5"
myco-static-compiled = { path = "../static-compiled/" }
myco-proxy = { path = "../proxy" }
