[package]
name = "myco-askama"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco = { path = "../myco" }
askama = "0.10.5"
mime-db = "1.1.0"

[dev-dependencies]
myco-smol-server = { path = "../smol-server" }
