[package]
name = "myco-smol-server"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-net = "1.5.0"
myco = { path = "../myco" }
smol = "1.2.5"
myco-http = { path = "../http" }
log = "0.4.13"
myco-server-common = { path = "../server-common" }
async-io = "1.3.1"

[target.'cfg(unix)'.dependencies]
signal-hook-async-std = "0.2.1"
signal-hook = "0.3.4"

[dev-dependencies]
env_logger = "0.8.3"
