[workspace]
members = [
  "askama",
  "async-std-server",
  "aws-lambda",
  "aws-lambda-example",
  "basic-auth",
  "cookies",
  "errors",
  "example",
  "http",
  "http-types",
  "logger",
  "myco",
  "openssl",
  "router",
  "rustls",
  "sessions",
  "smol-server",
  "static",
  "tera",
  "tokio-server",
  "websockets",
]
