[workspace]
members = [
  "askama",
  "http",
  "async-std-server",
  "basic-auth",
  "errors",
  "cookies",
  "example",
  "http-types",
  "logger",
  "myco",
  "router",
  "smol-server",
  "sessions",
  "websockets",
  "static",
  "tokio-server",
  "tera"
]
