[package]
name = "myco-router"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
routefinder = "0.2"
myco = { path = "../myco" }
log = "0.4.14"

[dev-dependencies]
env_logger = "0.8.3"
myco-smol-server = { path = "../smol-server" }
