[package]
name = "trillium-aws-lambda"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
log = "0.4.13"
tokio = { version = "1.1.0", features = ["rt", "net", "rt-multi-thread"] }
trillium-http = { path = "../http" }
futures-lite = "1.11.3"
serde_json = "1.0.61"
serde = "1.0.123"
serde_derive = "1.0.123"
base64 = "0.13.0"
lamedh_runtime = "0.3.0"

[dependencies.http-types]
git = "https://github.com/jbr/http-types"
branch = "trillium"
default-features = false
features = ["serde"]
