[package]
name = "trillium"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures-lite = "1.11.3"
log = "0.4.13"
trillium-http = { path = "../http" }
