[package]
name = "myco-sessions"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco-cookies = { path = "../cookies" }
myco = { path = "../myco" }
async-session = "2.0.1"
log = "0.4.13"
