[package]
name = "myco-server-common"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco = { path = "../myco" }
myco-http = { path = "../http" }
log = "0.4.14"
futures-lite = "1.11.3"
myco-tls-common = { path = "../tls-common/" }
