[package]
name = "myco-server-common"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
myco = { path = "../myco" }
myco-http = { path = "../http" }
log = "0.4.14"
