[package]
name = "trillium-http"
version = "0.0.1"
edition = "2018"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the http implementation for the trillium toolkit"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "README.md"
keywords = ["trillium", "http", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
unstable = []

[dependencies]
httparse = "1.3.4"
log = "0.4.13"
pin-project = "1.0.4"
thiserror = "1.0.23"
futures-lite = "1.11.3"
memmem = "0.1.1"
stopper = "0.2.0"
encoding_rs = "0.8.28"
http-types = { version = "0.0.1", default-features = false, package = "trillium-http-types" }

[dev-dependencies]
async-net = "1.5.0"
env_logger = "0.8.2"
smol = "1.2.5"
async-compat = "0.2.0"
async-io = "1.3.1"
trillium-client = { path = "../client" }
trillium-testing = { path = "../testing" }

[dev-dependencies.tokio]
version = "1.1.0"
features = ["rt", "net", "rt-multi-thread", "macros"]
