[package]
name = "myco-static-compiled"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6.0"
myco = { path = "../myco" }
mime-db = "1.1.0"
log = "0.4.14"

[dev-dependencies]
myco-smol-server = { path = "../smol-server" }
env_logger = "0.8.2"
