[package]
name = "myco-logger"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
myco = { path = "../myco" }
log = "0.4.13"
colored = "2.0.0"
chrono = "0.4.19"
size = "0.1.2"
