[package]
name = "myco-websockets"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-dup = "1.2.2"
async-tungstenite = "0.12.0"
base64 = "0.13.0"
futures-util = "0.3.12"
myco = { path = "../myco" }
pin-project = "1.0.4"
serde = "1.0.120"
serde_json = "1.0.61"
sha-1 = "0.9.2"
log = "0.4.13"

[dev-dependencies]
myco-smol-server = { path = "../smol-server/" }
env_logger = "0.8.2"
