[package]
name = "myco"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures-lite = "1.11.3"
async-dup = "1.2.2"
log = "0.4.13"
async-channel = "1.5.1"
async-net = "1.5.0"
http-types = { path = "../http-types", default-features = false }
myco-http = { path = "../http" }
