[package]
name = "myco-native-tls"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-native-tls = "0.3.3"
myco-tls-common = { path = "../tls-common" }
native-tls = "0.2.7"

[dev-dependencies]
env_logger = "0.8.2"
myco-smol-server = { path = "../smol-server" }
myco = { path = "../myco" }
