[package]
name = "trillium-tera"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
mime-db = "1.1.0"
tera = "1.6.1"
serde = "1.0.123"

[dev-dependencies]
trillium-smol-server = { path = "../smol-server" }
