[book]
authors = ["Jacob Rothstein"]
language = "en"
multilingual = false
src = "src"
title = "myco"

[rust]
edition = "2018"

[output.html.playground]
editable = false
copy-js = true
line-numbers = false
